apiVersion: v1
kind: Service
metadata:
  name: hostaliases-injector-webhook-svc
  labels:
    app: hostaliases-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: hostaliases-injector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostaliases-config
data:
  config: |
      - name: dataset
        label: dataset
        hostAliases:
        - ip: "1.2.3.4"
          hostnames:
          - "example.com"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostaliases-injector-webhook-deployment
  labels:
    app: hostaliases-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hostaliases-injector
    spec:
      containers:        
        - name: hostaliases-injector
          image: docker.io/rootfs/hostalias-webhook:latest
          imagePullPolicy: Always
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-private-key-file=/etc/webhook/certs/key.pem
            - -config-file=/etc/webhook/config
            - -v=5
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/
              readOnly: true              
      volumes:
           - name: webhook-certs
             secret:
               secretName: hostaliases-injector-webhook-certs
           - name: webhook-config
             configMap:
               name: hostaliases-config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: hostaliases-webhook-cfg-dp
  labels:
    app: hostaliases-injector-dp
webhooks:
  - name: hostaliases-injector-dp.webhook.io
    clientConfig:
      service:
        name: hostaliases-injector-webhook-svc
        namespace: default
        path: "/mutate-deployment"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations:  [ "CREATE" ]
        apiGroups:   ["extensions"]
        apiVersions: ["v1beta1"]
        resources:   ["deployments"]
    namespaceSelector:
      matchLabels:
        hostaliases-injector: enabled

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: hostaliases-webhook-cfg-job
  labels:
    app: hostaliases-injector-dp
webhooks:
  - name: hostaliases-injector-job.webhook.io
    clientConfig:
      service:
        name: hostaliases-injector-webhook-svc
        namespace: default
        path: "/mutate-job"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations:  [ "CREATE" ]
        apiGroups:   ["batch"]
        apiVersions: ["v1"]
        resources:   ["jobs"]
    namespaceSelector:
      matchLabels:
        hostaliases-injector: enabled
