apiVersion: v1
kind: ConfigMap
metadata:
  name: hostaliases-initializer
data:
  config: |
      - name: application
        label: application
        hostAliases:
            - ip: "127.0.0.1"
              hostnames:
                - "foo.local"
                - "bar.local"
            - ip: "10.1.2.3"
              hostnames:
                - "foo.remote"
                - "bar.remote"

